[package]
name = "miri"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
voicemeeter = {path = "../."}
[build-dependencies]
rustc_version = "0.4"
