[package]
name = "sync-a1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.5"
eyre = "0.6.12"
scopeguard = "1.2.0"
windows = { version = "0.62.0", features = ["Win32_Media_Audio_Endpoints", "Win32_Foundation", "Win32_System_Com", "Win32_System_Com_StructuredStorage", "Win32_System_Variant"] }
voicemeeter = {workspace = true, features = ["interface"] }
ctrlc = "3.5.0"
windows-core = "0.62.0"
