[package]
name = "voicemeeter"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "FFI bindings to Voicemeeter SDK"



[workspace]
members = ["voicemeeter-sys", "."]


[patch.crates-io]
bindgen = {git = "https://github.com/Emilgardis/rust-bindgen", branch = "dynamic-comments"}