pre-release-commit-message = "release {{crate_name}} {{version}}"
tag = false
push = false
publish = false
consolidate-commits = false
pre-release-replacements = [
  {file="CHANGELOG.md", search="Unreleased", replace="v{{version}}", prerelease=false},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}", prerelease=false},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n\n## [Unreleased] - ReleaseDate\n\n[Commits](https://github.com/Emilgardis/voicemeeter-sdk-rs/compare/v{{version}}...Unreleased)", prerelease=false},
  {file="README.md", search="voicemeeter/[a-z0-9\\.-]+/voicemeeter", replace="{{crate_name}}/{{version}}/{{crate_name}}", prerelease=true},
]