[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
bindgen = { version = "0.68.1" }
color-eyre="0.6.0"
pretty_assertions = "1.1.0"